### ISSUE TITLE
[Feat] 차단 기능 데이터 처리 추가

### ISSUE THREAD

**Issue by Choe-ju** [Team-TrackUs/Trackus_iOS#21]
## Feature
추가 예정인 기능에 대하여 설명해주세요.

## Todo
여러개의 기능이 추가될 예정이라면 카테고리를 나눠주세요.

### UserInfo 차단 사용자 추가
- [x] 내가 차단한 사람
- [x] 나를 차단한 사람

### 차단 관련 채팅 예외처리
- [x] 차단한 사용자 1대1 대화가 되지 않도록 예외 처리
