### ISSUE TITLE
[Feat] 채팅방 관련 Notification 기능 추가

### ISSUE THREAD

**Issue by Choe-ju** [Team-TrackUs/Trackus_iOS#34]
## Feature
채팅방 관련 Notification 기능 추가

## Todo
여러개의 기능이 추가될 예정이라면 카테고리를 나눠주세요.

### 채팅 Notification
- [x] 현재 열려있는 채팅방 알림 안뜨도록 제한
- [x] 알림 누를 경우 채팅방으로 view 이동
  - [ ] 백그라운드에서 안되는 부분 수정
  - [ ] 채팅방 나올 경우 알림 안뜨는 부분 수정
